### PR TITLE
Italian translation; few fixes along the way

### PR DESCRIPTION
**Pull request by frazzmark**
I fixed the 2 problems which made the app crash on first start.

### CODE REVIEW

**Comment by bparmentier** [comment]
I fixed the bugs in https://github.com/bparmentier/OpenBikeSharing/commit/47699dd5575dcdafa4f94b1cc84dad9bb4ada202. Could you merge this commit into your branch to resolve conflicts? And after that maybe squash your modifications into one commit to keep it clean.

**Comment by frazzmark** [comment]
Ok I'm not an expert on git but will try to do it.

**Comment by bparmentier** [comment]
Aw, sorry, I didn't see you fixed the conflicts!

Thank you! I'll try to release the new version very soon.

**Comment by frazzmark** [comment]
So... when will the new versione be published?

**Comment by bparmentier** [comment]
I didn't have much time for the last two months… I want to finish the widget, which is usable but not ready yet for a release.

About that, there are two new strings to translate in [`strings.xml`](https://github.com/bparmentier/OpenBikeSharing/blob/master/app/src/main/res/values/strings.xml) (under `<!-- Widget -->`).

I'm really sorry to make you wait, I do my best ;-)

**Pull request merged**
