### PR TITLE
Added SwipeRefreshLayout

### PR DESCRIPTION
**Pull request by frazzmark**
finally, the swiperefreshlayourt is ready. Now pull down to refresh the stations.

### CODE REVIEW

**Comment by frazzmark** [comment]
I have no idea why travis CI build fails, but I get a different error when merging the two repos and building the app locally with ./gradlew build

**Comment by bparmentier** [comment]
You didn't update your fork to the latest version. There were some changes in those files since your commit five months ago. Please take a look here : https://help.github.com/articles/syncing-a-fork/

**Comment by frazzmark** [comment]
Ah I see... I thought that wasn't strictly necessary.... Will do when I have time.
Il 08 mar 2016 08:35, Bruno Parmentier <notifications@github.com> ha scritto:You didn't update your fork to the latest version. There were some changes in those files since your commit five months ago. Please take a look here : https://help.github.com/articles/syncing-a-fork/

**Comment by frazzmark** [comment]
Done, but I still don't see why Travis ci build fails. I still get a different error on my computer.

**Comment by frazzmark** [comment]
@bparmentier everything solved, you can merge!

**Comment by bparmentier** [comment]
Thanks! There is still one problem; I don't know if it does the same to you, but on my phone, when I swipe left or right and my finger goes lightly down, the "change tab" action is cancelled.

**Comment by frazzmark** [comment]
Thanks for the suggestion! Luckily this problem is quite common, so I found quickly a solution.

**Pull request merged**
